SistemaAcademico/Controllers/AlunoController.cs
using SistemaAcademico.DAO;
using SistemaAcademico.Entidades;
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using static SistemaAcademico.Entidades.Aluno;

namespace SistemaAcademico.Controllers
{
    public class AlunoController : Controller
    {

        // GET: Aluno
        
        public ActionResult Index(int? sortOrder)
        {
            AlunoDAO dAO = new AlunoDAO();

   

            return View(dAO.BuscaParametro(sortOrder));

        }

        //Popula 3 turmas com 20 alunos -
        public ActionResult PopulaAluno()
        {
            //Instanciar DAO
            TurmaDAO dAOTurma = new TurmaDAO();
            AlunoDAO dAOAluno = new AlunoDAO();

            //Gerador de numeros 
            Random random = new Random();


            //Logica para adicionar 20 alunos em cada turma 

            using (SistemaContext context = new SistemaContext())
            {
                for (int y = 1; y <= 3; y++)
                {
                    //Criar uma turma
                    Turma turma = new Turma();
                    turma.Nome = "Turma " + y;
                    //Criar uma Lista de Alunos 
                    List<Aluno> ListaDeAlunos = new List<Aluno>();

                    for (int x = 1; x <= 20; x++)
                    {
                        Aluno aluno = new Aluno();
                        aluno.Nome = "Aluno " + x;
                        aluno.Matricula = (random.Next(1, 10000) + 10000);
                        aluno.Nota1 = random.Next(1, 10);
                        aluno.Nota2 = random.Next(1, 10);
                        aluno.Nota3 = random.Next(1, 10);
                        aluno.Turma = turma;
                        ListaDeAlunos.Add(aluno);
                    }
                    dAOTurma.Adiciona(turma);
                    dAOAluno.Adiciona(ListaDeAlunos);
                }

            }
            return RedirectToAction("Index");
        }

        //Popular notas da prova final e calcular as pessoas que ficaram de fato reprovadas. 
        public async Task<ActionResult> PopulaNotaFinalAsync()
        {
            //Instancia do DAO
            AlunoDAO dAO = new AlunoDAO();

            //Gerador de numeros 
            Random random = new Random();

            //Instancia de listas
            List<Aluno> alunos = new List<Aluno>();
            List<Aluno> ListaDeAlunos = new List<Aluno>(); //Lista para guardar os alunos a serem modificados 
            //Buscar alunos com status provaFinal
            alunos = dAO.BuscaEstadoFinal();

            //Gerar notas finais para esses alunos 
            foreach (Aluno aluno in alunos)
            {
                aluno.NotaFinal = random.Next(4, 10); //Atribuir nota
                ListaDeAlunos.Add(aluno); //Adicionar aluno na lista 
            }
            await dAO.Editar(ListaDeAlunos);
            return RedirectToAction("Index");
        }


        public ActionResult Delete()
        {
            using (SistemaContext c = new SistemaContext())
            {
                c.Turmas.RemoveRange(c.Turmas);
                c.SaveChanges();
            }
            return RedirectToAction("Index");
        }

    }
}

SistemaAcademico/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SistemaAcademico.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

SistemaAcademico/Controllers/PremiosController.cs
using SistemaAcademico.DAO;
using SistemaAcademico.Entidades;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace SistemaAcademico.Controllers
{
    public class PremiosController : Controller
    {
        private static AlunoDAO dAO = new AlunoDAO();
        private static List<Aluno> ListaDeAlunos = new List<Aluno>(); //Lista para salvar alunos editados temporariamente
        private Random random = new Random();


        // GET: Premios
        public ActionResult Index() //Exibe os 5 alunos que irão participar da competição 
        {
            //Listar 5 melhores notas
            AlunoDAO alunoDAO = new AlunoDAO();
            var Lista = dAO.BuscaParametro(10); // Retorna 5 alunos com a media mais alta 
            return View(Lista);
        }

        //Gerar nota para os 5 primeiros alunos 
        public async Task<ActionResult> GerarNotaEspecialAsync()
        {
            //Buscar pelos 5 primeiros alunos com a nota mais alta
            List<Aluno> alunos = new List<Aluno>();
            alunos = dAO.BuscaCompetidores();

            //Preencher a nota desses alunos com uma nata de competição
            foreach (Aluno aluno in alunos)
            {
                aluno.ProvaEspecial = random.Next(1, 10);
                ListaDeAlunos.Add(aluno);
            }

            //Salvo todas as ediçoes feitas 
            await dAO.Editar(ListaDeAlunos);

            //Retornar para o Index
            return RedirectToAction("MostrarRanking");
        }

        public ActionResult MostrarRanking() //Exibe o ranking dos alunos que participaram da competição
        {
            var Lista = dAO.BuscaCompetidores();
            ViewBag.Campeao = dAO.BuscaCampeao();
            return View(Lista.OrderByDescending(x => x.MediaCompeticao));
        }

    }
}

SistemaAcademico/Views/Aluno/Index.cshtml
@model IEnumerable<SistemaAcademico.Entidades.Aluno>



<table class="table table-bordered text-center table-striped table-hover"">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Turma)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Matricula)
        </th>
        <th>
            @Html.ActionLink("Nome", "Index", "Aluno", new { @sortOrder = 0 }, null)
        </th>
        <th>
            @Html.ActionLink("Status", "Index", "Aluno", new { @sortOrder = 1 }, null)
        </th>
        <th>
            @Html.ActionLink("Avaliação 1", "Index", "Aluno", new { @sortOrder = 2 }, null)
        </th>
        <th>
            @Html.ActionLink("Avaliação 2", "Index", "Aluno", new { @sortOrder = 3 }, null)
        </th>
        <th>
            @Html.ActionLink("Avaliação 3", "Index", "Aluno", new { @sortOrder = 4}, null)
        </th>
        <th>
            @Html.ActionLink("Avaliação Final", "Index", "Aluno", new { @sortOrder = 5 }, null)
        </th>
        <th>
            @Html.ActionLink("Média Final","Index","Aluno", new { @sortOrder = 8}, null)
            </th>
        <th>
            @Html.ActionLink("Avaliação da Competição", "Index", "Aluno", new { @sortOrder = 11  }, null)
        </th>
        <th>
            @Html.ActionLink("Média da Competição", "Index", "Aluno", new { @sortOrder = 9 }, null)
        </th>
    </tr>

    @foreach (var item in Model)
    {

        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Turma.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Matricula)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            @if (item.Status == SistemaAcademico.Entidades.Aluno._Status.Reprovado)
            {
                <td class="table-danger">
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
            }
            else if (item.Status == SistemaAcademico.Entidades.Aluno._Status.ProvaFinal)
            {
                <td class="table-warning">
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
            }
            else
            {
                <td class="table-success">
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
            }

            <td>
                @Html.DisplayFor(modelItem => item.Nota1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nota2)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nota3)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NotaFinal)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MediaFinalComTodasAsProvas)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProvaEspecial)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MediaCompeticao)
            </td>

        </tr>
    }

</table>

SistemaAcademico/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

SistemaAcademico/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

SistemaAcademico/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

SistemaAcademico/Views/Premios/Index.cshtml
@model IEnumerable<SistemaAcademico.Entidades.Aluno>

<div class="justify-content-md-center">
    <h1 class="text-center"> MELHORES ALUNOS</h1>
</div>


<table class="table table-bordered text-center table-striped table-hover">
    <tr>
        <th>
            Ranking
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Turma)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Matricula)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nota1)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nota2)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nota3)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NotaFinal)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MediaFinalComTodasAsProvas)
        </th>

    </tr>
    @{
        int x = 0;
    }
    @foreach (var item in Model)
    {
        <tr>
            <td>@{x = x + 1;} @x</td>
            <td>
                @Html.DisplayFor(modelItem => item.Turma.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Matricula)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nota1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nota2)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nota3)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NotaFinal)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MediaFinalComTodasAsProvas)
            </td>
        </tr>
    }

</table>

SistemaAcademico/Views/Premios/MostrarRanking.cshtml
@model IEnumerable<SistemaAcademico.Entidades.Aluno>

<div class="justify-content-md-center">
    <h1 class="text-center">COMPETIDORES</h1>
</div>
<table class="table table-bordered text-center table-striped table-hover">
    <tr>
        <th>
            Posição
            </th>
        <th>
            @Html.DisplayNameFor(model => model.Turma.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Matricula)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nota1)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nota2)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nota3)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NotaFinal)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MediaFinalComTodasAsProvas)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProvaEspecial)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MediaCompeticao)
        </th>
    </tr>
    @{
        int x = 0;
    }
    @foreach (var item in Model)
    {
        <tr>
            <td>@{x = x + 1;} @x</td>
            <td>
                @Html.DisplayFor(modelItem => item.Turma.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Matricula)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nota1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nota2)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nota3)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NotaFinal)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MediaFinalComTodasAsProvas)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProvaEspecial)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MediaCompeticao)
            </td>

        </tr>
    }

</table>
<div class="justify-content-md-center">
    <h1 class="text-center">VENCEDOR</h1>
</div>
<div>
    <table class="table table-bordered text-center table-striped table-hover" ">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Turma.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Matricula)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nota1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nota2)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nota3)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NotaFinal)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MediaFinalComTodasAsProvas)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProvaEspecial)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MediaCompeticao)
            </th>
        </tr>
        @foreach (var item in ViewBag.Campeao)
        {
            <tr>
                <td>
                    @item.Nome
                </td>
                <td>
                    @item.Matricula
                </td>
                <td>
                    @item.Nome
                </td>
                <td>
                    @item.Status
                </td>
                <td>
                    @item.Nota1
                </td>
                <td>
                    @item.Nota2
                </td>
                <td>
                    @item.Nota3
                </td>
                <td>
                    @item.NotaFinal
                </td>
                <td>
                    @item.MediaFinalComTodasAsProvas
                </td>
                <td>
                    @item.ProvaEspecial
                </td>
                <td>
                    @item.MediaCompeticao
                </td>

            </tr>
        }
    </table>
</div>

SistemaAcademico/Views/Shared/_Header.cshtml
<nav class="navbar navbar-expand-lg navbar-light bg-light fix fixed-top">
    <a class="navbar-brand" href="@Url.Action("Index","Aluno")">Home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Competição
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="@Url.Action("Index","Premios")">Visualizar competidores</a>
                    <a class="dropdown-item" href="@Url.Action("GerarNotaEspecialAsync","Premios")">Simular Avaliação Competitiva</a>
                    <a class="dropdown-item" href="@Url.Action("MostrarRanking","Premios")">Visualizar Ranking</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Aluno
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="@Url.Action("Index","Aluno")">Lista de alunos</a>
                    <a class="dropdown-item" href="@Url.Action("PopulaAluno","Aluno")">Simular Cadastros</a>
                    <a class="dropdown-item" href="@Url.Action("PopulaNotaFinalAsync","Aluno")">Simular Nota Final</a>
                    <a class="dropdown-item" href="@Url.Action("Delete","Aluno")">Resetar Sistema</a>
                </div>
            </li>
        </ul>
    </div>
</nav>

SistemaAcademico/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meu Aplicativo ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @Html.Partial("_Header")
    <div class="p-4">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>